name: Main Regression

on:
  push:
    branches: [ main ]

jobs:
  api-regression:
    name: API Regression
    uses: ./.github/workflows/reusable-test-runner.yml
    with:
      test_layer: api
      tag: regression

  ui-regression:
    name: UI Regression
    uses: ./.github/workflows/reusable-test-runner.yml
    with:
      test_layer: ui
      tag: regression
