name: PR Smoke

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  api-smoke:
    name: API Smoke
    uses: ./.github/workflows/reusable-test-runner.yml
    with:
      test_layer: api
      tag: smoke

  ui-smoke:
    name: UI Smoke
    uses: ./.github/workflows/reusable-test-runner.yml
    with:
      test_layer: ui
      tag: smoke
